spring:
  profiles:
    active: local
  application:
    name: seegene-platform-mvc-example
  datasource:
    poolName: sample-domain-cp
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/example?useSSL=false&allowPublicKeyRetrieval=true"
    username: root
    password: root
    auto-commit: false
    connectionTimeout: 3000
    idleTimeout: 0
    maxLifetime: 60000
    maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show-sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 500
          fetch_size: 500
          batch_versioned_data: true

jwt:
  token-validity-in-seconds: 1800 # * 1000 = 30분
  refresh-token-validity-in-seconds: 5400 # * 1000 = 90분
  server:
    api-auth-key: "localseegeneapiauthkeyinsilicoaaaaaaaa"


app:
  cors:
    allowed-origins: http://localhost:3000

server:
  port: 8081
  servlet:
    context-path: /api

logging:
  com.demo.sample: debug
  config: classpath:logback-local.xml



---
spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: prd